name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      geckodriver:
        image: selenium/standalone-firefox:133.0-20250101
        ports:
          - 4444:4444
        options: >
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
